#!/usr/bin/python3
print("The Zen of Python, by Tim Peters")
print("Beautiful is better than ugly.")
print("Explicit is better than implicit.Explicit is better than implicit.")
print("Simple is better than complex.")
print("Complex is better than complicated.")
print("Flat is better than nested.")
print("Sparse is better than dense.")
print("Readability counts.")
print("Special cases aren't special enough to break the rules.")
print("Although practicality beats purity.")
